// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jvyqdzisqpxerwjkydhc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp2eXFkemlzcXB4ZXJ3amt5ZGhjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0NjE2MTcsImV4cCI6MjA3NDAzNzYxN30.xeov22Xy5UYYEOYlr9MEkJmddBI4he7LXdS8kW5DWbw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});